"""Initial tables

Revision ID: 9d0a9497db25
Revises: 
Create Date: 2026-05-09 13:12:12.312132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0a9497db25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('images', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('images', 'name')
    # ### end Alembic commands ###
